### ISSUE TITLE
It seems non-ascii unicode chars are getting stripped from js files

### ISSUE THREAD

**Issue by gekola** [tenex/rails-assets#223]
E.g. rails-assets-d3 (I checked versions 3.5.5, 3.5.4 and 3.5.3), file app/assets/javascripts/d3/d3.js:1261 should have pi and epsilon symbols as variables names (as it used to), but recently it became not to (so syntax error is arised).
This is caused by processing files content with `encode!('UTF-8', 'binary', invalid: :replace, undef: :replace, replace: '')`.

**Comment by melnikaite** [comment]
+1

**Comment by sheerun** [comment]
Thanks for noticing this. It's most likely because of https://github.com/rails-assets/rails-assets/commit/742f2d12c55f2933a428fb051a884a08a6a232fa

**Comment by sheerun** [comment]
@gekola @melnikaite I fixed this issue and rebuilt d3 (other components rebuild are pending).

Could you confirm this issue is fixed? You may need to uninstall rails-assets gems manually first..

**Comment by melnikaite** [comment]
Thanks a lot! Build passed

**Comment by donbobka** [comment]
@sheerun, the same problem with `rails-assets-moment` still exists in `/app/assets/javascripts/moment/locale/ru.js`

**Comment by donbobka** [comment]
Problem with `rails-assets-moment` resolved
