### ISSUE TITLE
Server error on bundle from rails-assets.org

### ISSUE THREAD

**Issue by zinkkrysty** [tenex/rails-assets#408]
```
Fetching gem metadata from https://rails-assets.org/.
Retrying dependency api due to error (2/4): Bundler::HTTPError Net::HTTPInternalServerError: <!DOCTYPE html>
<html>
<head>
  <title>We're sorry, but something went wrong (500)</title>
  <style>
  body {
    background-color: #EFEFEF;
    color: #2E2F30;
    text-align: center;
    font-family: arial, sans-serif;
  }

  div.dialog {
    width: 25em;
    margin: 4em auto 0 auto;
    border: 1px solid #CCC;
    border-right-color: #999;
```

**Comment by schuetzm** [comment]
Can confirm, example URL:
GET https://rails-assets.org/api/v1/dependencies?gems=rails

**Comment by zinkkrysty** [comment]
Fortunately for me I only had one asset that was loaded from rails-assets.org so the decision of removing it was easy. It's not nice with these 3rd party dependencies that have no contingency plan when errors occur.

**Comment by WaKeMaTTa** [comment]
Any news about this? cc/ @tenex

**Comment by lakehouseru** [comment]
+1

**Comment by joshjordan** [comment]
Hi friends, our fail over mechanism did not work as expected. We had some alarms go off, but they did not wake me up. I'm on it now.

**Comment by pheisiph** [comment]
> remote: Verifying deploy.... done.

bundler just completed successfully for us. Thanks Josh!

**Comment by harrisonhm** [comment]
Fixed for us as well. Thank you Josh :)

**Comment by benlovell** [comment]
Thanks @joshjordan <3

**Comment by joshjordan** [comment]
All set, friends. We still get lingering open file handles that mess us up sometimes. We're gathering more data to solve it.

As a reminder, if rails-assets is useful to you, we accept donations on the homepage to keep it running :) It is not free for us, both in time and in operational costs. Thanks, all!

**Comment by hut8** [comment]
Hey everyone,

I just did a postmortem. Long ago, we had implemented a solid fail-over plan. Our primary servers are on the east coast. We have a totally redundant second deployment (complete with database, all the gems, etc) that's hosted on the west coast so there's no single point of failure for any part of rails-assets.org. It's on standby 24/7, waiting to accept requests.

We're using Amazon Route 53 along with some health checks to actually perform the failover, and if you look closely you'll see that we have a very low TTL on our domain's A records to minimize downtime during an outage on the primary. When I had configured the health check, apparently I configured it in such a way that a disk outage (which is clearly a disaster) would not actually trigger a failure. Hitting http://rails-assets.org and having that issue a 301 redirect in a timely manner to https://rails-assets.org was enough to define "success." I've rectified that so now it is a bit more stringent about how "success" is defined.

Also, the primary cause of this was just running out of disk space due to logs, which was due to the log rotation changing after we integrated this service with our ELK stack. It ran out quite quickly, so we didn't wake up in time to realize that the log rotation was broken. This is also fixed.
