### ISSUE TITLE
Could not fetch specs

### ISSUE THREAD

**Issue by KacperPucek** [tenex/rails-assets#73]
Hey, I am getting `Could not fetch specs from https://rails-assets.org/` when trying to fetch following gem

```
source "https://rails-assets.org" do
  gem "rails-assets-normalize-css", "~> 3.0.2"
end
```

Is this by any chance connected with the moving to the new servers?

**Comment by fschwahn** [comment]
Same here, I'm receiving the following error:
```
Retrying dependency api due to error (3/6): Bundler::HTTPError Net::HTTPServiceUnavailable: <h2>This website is under heavy load (queue full)</h2><p>We're sorry, too many people are accessing this website at the same time. We're working on this problem. Please try again later.</p>
```

**Comment by hut8** [comment]
Hey,

Sorry for the radio silence, I was trying to put out the fire that caused this. These should be fixed. This is actually caused by a memory explosion issue in the worker processes that sort of spiraled out of control. I will spend some time today trying to track down where this happens. I apologize for the inconvenience.

**Comment by RadoMark** [comment]
Still occuring, both for _old_ `rails-assets.org` and the _new_ `rails-assets.tenex.tech`:
```
Fetching source index from http://rails-assets.tenex.tech/
Retrying fetcher due to error (2/4): Bundler::HTTPError Could not fetch specs from http://rails-assets.tenex.tech/
Retrying fetcher due to error (3/4): Bundler::HTTPError Could not fetch specs from http://rails-assets.tenex.tech/
Retrying fetcher due to error (4/4): Bundler::HTTPError Could not fetch specs from http://rails-assets.tenex.tech/
Could not fetch specs from http://rails-assets.tenex.tech/
```
Additionally, I get `Could not verify the SSL certificate` when trying to use it with `https`.

**Comment by hut8** [comment]
Hey @RadoMark. I need some additional information.

* Could you please run `bundle install --verbose`?
* What is your DNS resolving rails-assets.tenex.tech to? 

https://www.ssllabs.com/ssltest/analyze.html?d=rails-assets.tenex.tech&latest -- looks okay. The certs are only good for 90 days, but that shouldn't be an issue because they're renewed via a cron job. Looks like it was last updated only 4 days ago.

`http(s)://rails-assets.tenex.tech` issues a 301 redirect to `https://rails-assets.org`.

**Comment by RadoMark** [comment]
Duplicate: #74

**Comment by hut8** [comment]
@RadoMark thanks -- can you confirm you're using jRuby?

**Comment by RadoMark** [comment]
@hut8 Yes. I work with @KacperPucek, we met the issue together.
